# A2C configuration for Trading Bot Simulator

# Inherit from default config
defaults: [default]

train:
  algo: a2c
  total_timesteps: 100000
  learning_rate: 0.0007
  n_steps: 5
  gamma: 0.99
  gae_lambda: 1.0
  ent_coef: 0.01
  vf_coef: 0.25
  max_grad_norm: 0.5
  rms_prop_eps: 1e-05
  use_rms_prop: true
  use_sde: false
  sde_sample_freq: -1
  normalize_advantage: false
  tensorboard_log: runs/a2c/tensorboard
  policy_kwargs:
    net_arch: [64, 64]
    activation_fn: tanh
