# Default configuration for Trading Bot Simulator

data:
  source: yfinance  # or csv
  ticker: BTC-USD
  interval: 1d
  start: 2022-01-01
  end: 2022-12-31
  cache: true
  cache_dir: data/cache

env:
  window_size: 64
  fee_bps: 10  # 0.1% fee
  slippage_bps: 5  # 0.05% slippage
  reward: profit_increment
  max_drawdown: 0.3
  stop_loss: 0.2
  allow_short: false

train:
  algo: ppo
  total_timesteps: 100000
  seed: 42
  train_split: 0.8
  test_split: 0.2
  eval_freq: 10000
  save_freq: 10000

features:
  sma_periods: [10, 20, 50]
  ema_periods: [12, 26]
  rsi_length: 14
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  bollinger_length: 20
  bollinger_std: 2

portfolio:
  starting_cash: 10000
  allow_short: false
  leverage: 1.0
  position_sizing: 1.0  # Use full available cash per trade

evaluation:
  baseline_strategies: [buy_and_hold, sma_crossover]
  sma_short: 10
  sma_long: 50
  risk_free_rate: 0.02

logging:
  level: INFO
  format: json
  file: logs/tbs.log
