# DQN configuration for Trading Bot Simulator

# Inherit from default config
defaults: [default]

train:
  algo: dqn
  total_timesteps: 150000
  learning_rate: 0.0001
  buffer_size: 1000000
  learning_starts: 50000
  batch_size: 32
  tau: 1.0
  gamma: 0.99
  train_freq: 4
  gradient_steps: 1
  target_update_interval: 10000
  exploration_fraction: 0.1
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.05
  max_grad_norm: 10
  tensorboard_log: runs/dqn/tensorboard
  policy_kwargs:
    net_arch: [64, 64]
    activation_fn: relu
