data:
  source: yfinance
  ticker: BTC-USD
  interval: 1d
  start: '2023-01-01'
  end: null
  cache: true
  cache_dir: data/cache
env:
  window_size: 64
  fee_bps: 10
  slippage_bps: 5
  reward: profit_increment
  max_drawdown: 0.3
  stop_loss: 0.2
  allow_short: false
train:
  algo: ppo
  total_timesteps: 5000
  seed: 42
  train_split: 0.8
  test_split: 0.2
  eval_freq: 10000
  save_freq: 10000
  learning_rate: 0.0003
  batch_size: 64
  n_steps: 2048
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  normalize_advantage: true
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  use_sde: false
  sde_sample_freq: -1
  target_kl: null
  tensorboard_log: runs/ppo/tensorboard
  policy_kwargs:
    net_arch:
      pi:
      - 64
      - 64
      vf:
      - 64
      - 64
features:
  sma_periods:
  - 10
  - 20
  - 50
  ema_periods:
  - 12
  - 26
  rsi_length: 14
  macd_fast: 12
  macd_slow: 26
  macd_signal: 9
  bollinger_length: 20
  bollinger_std: 2
portfolio:
  starting_cash: 10000
  allow_short: false
  leverage: 1.0
  position_sizing: 1.0
evaluation:
  baseline_strategies:
  - buy_and_hold
  - sma_crossover
  sma_short: 10
  sma_long: 50
  risk_free_rate: 0.02
logging:
  level: INFO
  format: json
  file: logs/tbs.log
defaults:
- default
